-- Add show_in_live_feed column to twitter_accounts
ALTER TABLE twitter_accounts ADD COLUMN show_in_live_feed INTEGER DEFAULT 0 NOT NULL;

-- Mark personal accounts for live feed (kişisel hesaplar)
UPDATE twitter_accounts 
SET show_in_live_feed = 1 
WHERE username IN (
    'RTErdogan',
    'dbdevletbahceli',
    'eczozgurozel',
    'nevsinmengu',
    'HakanFidan',
    'erkbas',
    'cuneytozdemir',
    'haskologlu',
    'sakinan1968',
    'eafyoncu',
    'm_cemilkilic',
    'merdanyanardag',
    'MTanal',
    'Selcuk',
    'E_SemihYalcin',
    'buyukataman',
    'celal_adan',
    'YildizFeti',
    'candundaradasi',
    'kilicdarogluk',
    'ekrem_imamoglu',
    'mansuryavas06',
    'meral_aksener',
    'alibabacan',
    'MDervisogluTR',
    'erbakanfatih',
    'eceuner12',
    'emrahgulsunar',
    'ismailari_',
    'ismailsaymaz',
    'kucukkayaismail',
    'muratagirel',
    'baristerkoglu',
    'barispehlivan',
    'mahfiegilmez',
    'OzgrDemirtas',
    'emrealkin1969',
    'iriscibre',
    'mustafasonmez',
    'ugurses',
    'senolguldur',
    'umitozdag',
    'MuharremInce',
    'Ahmet_Davutoglu',
    'Temel_Karamollaoglu',
    'fahrettinaltun',
    'yagosabuncuoglu',
    'ertemsener',
    'ugur_dundar',
    'fatihportakal',
    'yilmazozdil',
    'sedat_peker',
    'memetsimsek',
    'barisyarkadas',
    'saygi_ozturk',
    'muratyetkin2',
    'fehimtastekin',
    'abdulkadir_selvi',
    'metinfeyzioglu',
    'gonencgurkaynak'
);
